language: php
php:
  - "5.6"
  - "7.0"
  - "hhvm"

before_script:
  - composer self-update
  - composer install

script:
  - php vendor/phpunit/phpunit/phpunit tests/

matrix:
     allow_failures:
         - php: "hhvm"
branches:
  only:
    - master
 
